driving-school-1/config/routes.rb
Rails.application.routes.draw do
  devise_for :instructors
  devise_for :students

  get 'main/index'
  get '/students/dashboard', to: 'main#student_dashboard'
  get '/instructors/dashboard', to: 'main#instructor_dashboard'
  get '/registration_confirmation', to: "main#registration_confirmation"
  get '/lessons/:id/confirmation', to: "lessons#confirmation", as: 'lessons_confirmation'
  root 'main#index'

end

driving-school-1/app/models/instructor.rb
class Instructor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

		 has_many :lessons, dependent: :destroy
		 
		 
end

driving-school-1/app/models/lesson.rb
class Lesson < ActiveRecord::Base
  
    belongs_to :instructor
    belongs_to :student
    
    
    def self.check_instructor(lesson)
        @instructor = lesson.user
        @instructor.lessons.each do |appoint|
            if appoint.id != lesson.id
                if (appoint.lesson_date == lesson.lesson_date)
                    if ((lesson.lesson_time + 1.hour) > appoint.lesson_time) and ((appoint.lesson_time + 1.hour) > lesson.lesson_time)
                        return true
                    end
                end
            end
        end
        return false
    end
    
end

driving-school-1/app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
		 
		 has_many :lessons, dependent: :destroy
		 
end

driving-school-1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  def after_sign_up_path_for(resource)
    registration_confirmation_path
  end
  
  def after_sign_in_path_for(resource)
    if current_instructor
      instructors_dashboard_path
    elsif current_student
      students_dashboard_path
    end
  end
  
  
end

driving-school-1/app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

    before_action :authenticate_student!
    before_action :check_lesson, only: [:new, :create]
	
    def new
        @instructor = instructor.find(params[:instructor_id])
        @lesson = @instructor.lessons.new
    end
    
    def create
        @instructor = instructor.find(params[:instructor_id])
        @lesson = @instructor.lessons.new(lesson_params)
        @lesson.save
        if lesson.check_instructor(@lesson)
            @lesson.destroy
           return redirect_to new_lesson_path(@instructor), notice: "The time slot is not available." 
        else
            redirect_to lessons_confirmation_path(@lesson), notice: "lesson Created"
        end
    end
    
    def destroy
       @lesson = lesson.find(params[:id])
       @lesson.destroy
       redirect_to instructors_dashboard_path, notice: "Your lesson was Canceled."
    end
    
    def confirmation
        @lesson = lesson.find(params[:id])
    end
    
    private
    
    def lesson_params
        params.require(:lesson).permit(:student_id,:lesson_date ,:lesson_time)
    end
end

driving-school-1/app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        @instructors = Instructor.all
    end
    
    def instructor
       @instructors = Instructor.all
    end
	
	def instructor_dashboard
        
    end
    
    def student_dashboard
        
    end
    

end

driving-school-1/app/helpers/application_helper.rb
module ApplicationHelper
end

driving-school-1/app/helpers/lessons_helper.rb
module LessonsHelper
end

driving-school-1/app/helpers/main_helper.rb
module MainHelper
end

driving-school-1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Driving School</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- START OF NAVIGATION BAR -->
<nav class="topnav" id="myTopnav">
  <%= link_to "Home", root_path%> 

                  <% if instructor_signed_in? %>
                    
                        <a  href="/instructors/dashboard">Dashboard</a>
                   
                   
                        <a  href="/instructors/sign_out" data-method="delete">Log Out</a>
                   
                <% elsif student_signed_in? %>
                    
                        <a  href="/students/dashboard">Dashboard</a>
                    
                    
                        <a  href="/students/sign_out" data-method="delete">Log Out</a>
                    
                <% else %>
                   
                        <a  href="/instructors/sign_in">Sign In As Instructor</a>
                  
                   
                        <a  href="/students/sign_in">Sign In As Student</a>
               
                <% end %>
            </ul>
			
			
</nav>
  <!-- END OF NAVIGATION BAR -->

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

driving-school-1/app/views/lessons/confirmation.html.erb
<div class="gallery-single-wrapper clearfix confirm">
    <article class="gallery-single">
        <div class="row">
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
                <div class="side-content clearfix">
                    <!--gallery item title-->
                    <center><h1 class="entry-title">lesson Confirmation</h1></center>
                    
                    <!--gallery item detail-->
                    <div class="entry-content">
                        <p>Thank You for booking an lesson at Bristall Medical Centre</p>
                        <p>Your lesson details have been sent to you by email and the details is as follows</p>
                        
                        <blockquote><center><h1 class="entry-title">lesson Details</h1>
                            <p><strong>Instructor:</strong> <%= @lesson.user.title %> <%= @lesson.user.first_name %> <%= @lesson.user.last_name %></p>
                            <p><strong>Date:</strong> <%= @lesson.lesson_date %></p>
                            <p><strong>Time:</strong> <%= @lesson.lesson_time.strftime("%H:%M:%S") %></p></center>
                        </blockquote>
                        
                    </div>
                </div>
            </div>    
        </div>
    </article>    
</div>  

driving-school-1/app/views/lessons/new.html.erb
<div class="appoint-page clearfix">
    <div class="container">
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-10">
                <article class="page type-page status-publish hentry clearfix">
                    <div class="entry-content text-center">
                        <h2 >Make an lesson with <%= @instructor.title %> <%= @instructor.first_name %> <%= @instructor.last_name %></h2>
                    </div>
                </article>

                <!--lesson form-->
                <div class="appoint-section clearfix">
                    <div class="top-icon"><img src="/appoint-form-top.png" alt=""/></div>
                    <div id="lesson_form_main">
                    <%= form_for @lesson do |f| %>
                        <div class="row">

                        <div class="row">
                            <div class="col-md-6">
                            <%= f.label :lesson_date %>    
                            <%= f.date_field :lesson_date, min: Date.today, :required => :true %>  
                            </div>
                            <div class="col-md-6 appoint_time">
                                <%= f.label :lesson_time %> 
                                <%= f.time_select :lesson_time, :start_hour => 10, :end_hour => 17, :minute_step => 15, :required => :true %>
                            </div>
                        </div>

                        <%= hidden_field_tag "instructor_id", params[:format] %>
                        <%= f.hidden_field :student_id, value: current_student.id %>
                        <center><%= f.submit class:"lesson-button form-submit-btn" %></center>
                    <% end %>
                  </div>  
                </div>
            </div>
            <div class="col-sm-1"></div>
        </div>

    </div>
</div>

driving-school-1/app/views/lessons/old_new.html.erb
This appointment will be with
<%= @doctor.title %> <%= @doctor.first_name %> <%= @doctor.last_name %>
<br/>
<%= form_for @appointment do |f| %>
  
  
  <div class="field">
    <%= f.label :appointment_date %>
    <%= f.date_field :appointment_date, min: Date.today, :required => :true %>
  </div>
  
  <div class="field">
    <%= f.label :appointment_time %>
    <%= f.time_select :appointment_time, :start_hour => 10, :end_hour => 17, :minute_step => 15 %>
  </div>
  
  <div class="field">
    <%= f.label :reason %>
    <%= f.text_area :reason %>
  </div>
  
  <%= hidden_field_tag "doctor_id", params[:format] %>
  <%= f.hidden_field :client_id, value: current_client.id %>
  
  <div>
    <%= f.submit %>
  </div>
<% end %>

driving-school-1/app/views/main/index.html.erb
<h1>Main#index</h1>
<p>app/views/main/index.html.erb</p>


<div class="row">
            
            <% @instructors.each do |instructor| %>
            <div class="col-md-4 col-sm-6 ">
                    <div class="text-content">                  
                            <h5 class="entry-title"><a href="/instructors/<%=instructor.id%>"><%= instructor.email %></a></h5>
							<%#= link_to (image_tag instructor.img_url,:size => "100x125"),instructor %>
                    </div>
            </div>
            <% end %>
 
 
 </div>

driving-school-1/app/views/main/instructor_dashboard.html.erb
<div class="doctors-posts doctors-page clearfix">
    <div class="container">
        <div class="blog-page-single clearfix">
            <div class="full-width-contents">
                <div class="entry-content text-center">
                    <h2>Appointments</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="container text-center">
        <div class="blog-page-single clearfix">
            <article class="page clearfix">
                <div class="page-contents">

                </div>
            </article>
        </div>
    </div>
</div>    

driving-school-1/app/views/main/student_dashboard.html.erb
<div class="instructors-posts instructors-page clearfix">
    <div class="container">
        <div class="blog-page-single clearfix">
            <div class="full-width-contents">
                <div class="entry-content text-center">
                    <h2>lessons</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="container text-center">
        <div class="blog-page-single clearfix">
            <article class="page clearfix">
                <div class="page-contents">
                    <!--detail sample page-->

                </div>
            </article>
        </div>
    </div>
</div>   

driving-school-1/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>